DATASET:
  DATASET_NAME: 'MANO'
  REMESH: False
OPT:
  PEAK_LR: 3.0e-3
  END_LR: 1.0e-4
  FT_LR: 1.0e-4
  WARMUP_STEPS: 100
  EVAL_PER_EPOCHS: 500
NODE:
  N_ODE_STEPS: 10
  USE_DIV_FREE: False
  ACTIVATION_FUNC: "gelu"
BONE_SAMPLING:
  N_TISSUE_SAMPLES_PER_ITER: 2000
  N_RIGID_SAMPLES_PER_BONE: 50
  AXIS_RADII:
    0: [ 0.05 ]
    1: [ 0.1 ]
    2: [ 0.1 ]
    3: [ 0.05 ]
    4: [ 0.1 ]
    5: [ 0.1 ]
    6: [ 0.05 ]
    7: [ 0.1 ]
    8: [ 0.1 ]
    9: [ 0.05 ]
    10: [ 0.1 ]
    11: [ 0.1 ]
    12: [ 0.1 ]
    13: [ 0.1 ]
    14: [ 0.1 ]
    15: [ 0.1 ]
    16: [ 0.1 ]
    17: [ 0.1 ]
    18: [ 0.1 ]
    20: [ 0.1 ]
VARIFOLD_INITIALISATION:
  SIGMAS: [0.5, 0.25]
  SIGMA_SPHS: [0.5, 0.5]
  ITERS_PER_LENGTHSCALE: [1000, 1000]
NORMAL_CYCLES:
  SIGMAS: [0.25, 0.1]
  ITERS_PER_LENGTHSCALE: [1000, 1000]
CONSTRAINTS:
  BONE_SAMPLE_EP: 1.0e1
  BONE_SAMPLE_TRAJ: 1.0
  SURFACE_ACAP: 2.0e1 #5.0e3
  TISSUE_ACAP: 1.0e1
  KEY_POINTS_EP: 0.0
FINE_TUNING:
  USE_FINE_TUNING: True
  FT_NUM_ITERS: 1000
  COMPRESS_SOURCE: False
  COMPRESS_TARGET: False
  BONE_SAMPLE_EP: 2.0e2
  BONE_SAMPLE_TRAJ: 5.0
  SURFACE_ACAP: 2.0e1
  TISSUE_ACAP: 1.0e1
  KEY_POINTS_EP: 0.0
COMPRESSION:
  COMPRESS_SOURCE: False
  COMPRESS_TARGET: True
  COMPRESSED_VARIFOLD_SOURCE_SIZE: 4000
  COMPRESSED_VARIFOLD_TARGET_SIZE: 4000
  COMPRESSED_NORMAL_CYCLE_SOURCE_SIZE: 6000
  COMPRESSED_NORMAL_CYCLE_TARGET_SIZE: 6000
RESULTS:
  LOAD_FROM_FILE: False
  RESULTS_DIR: 'results/'
  EVAL_TRAINGING_DATA: False
  PERCENTAGE_EVAL_SEQ: 10.0